try {
  console.log(naoExisto)
} catch(err) {
  console.log('naoExisto não existe')
  // console.log(err) // exibirá o log do erro
}